// Generated by ts-to-zod
import { z } from "zod";

const phoneRegex = new RegExp(
  /^([+]?[\s0-9]+)?(\d{3}|[(]?[0-9]+[)])?([-]?[\s]?[0-9])+$/
);

const emailRegex= new RegExp(
  /^[^\s@]+@[^\s@]+\.[^\s@]+$/
)

export const contactFormInputsSchema = z.object({
  firstName: z.string().min(1, { message: 'Required' }),
  lastName: z.string().min(1, { message: 'Required' }),
  email: z.string().regex(emailRegex, 'Please enter a valid email'),
  phoneNumber: z.string().regex(phoneRegex, 'Please enter a valid phone number'),
  message: z.string().min(1, { message: 'Required' }),
});
