// Generated by ts-to-zod
import { z } from "zod";

export const contactFormInputsSchema = z.object({
  firstName: z.string().min(1, { message: 'Required' }),
  lastName: z.string().min(1, { message: 'Required' }),
  email: z.string().min(1, { message: 'Required' }),
  phoneNumber: z.string().min(1, { message: 'Required' }),
  message: z.string().min(1, { message: 'Required' }),
});
